image: mcr.microsoft.com/dotnet/sdk:9.0

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          script:
            - dotnet test ComoGastoMinhaGrana.sln --configuration Release
      - step:
          name: Build and Push to Docker Hub
          services:
            - docker
          script:
            - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
            - docker build -t $DOCKERHUB_USERNAME/cgmg-api:latest -f src/ComoGastoMinhaGrana.Api/Dockerfile .
            - docker build -t $DOCKERHUB_USERNAME/cgmg-worker:latest -f src/ComoGastoMinhaGrana.Worker/Dockerfile .
            - docker build -t $DOCKERHUB_USERNAME/cgmg-ui:latest ./ComoGastoMinhaGrana.UI
            - docker push $DOCKERHUB_USERNAME/cgmg-api:latest
            - docker push $DOCKERHUB_USERNAME/cgmg-worker:latest
            - docker push $DOCKERHUB_USERNAME/cgmg-ui:latest
      - step:
          name: Deploy to VPS
          script:
            - pipe: atlassian/ssh-run:0.8.1
              variables:
                SSH_USER: 'root'
                SERVER: $SERVER_IP
                COMMAND: |
                  cd ~/app/cgmg
                  docker compose pull
                  docker compose up -d
                  docker image prune -f
